Outputs:
  TestOutput:
    Value: Hello World!
Resources:
  TestFunctionServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TestingStack/TestFunction/ServiceRole/Resource
  TestFunction22AD90FC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: 'def test():\n    return "Success!"'
      Handler: index.test
      Role:
        Fn::GetAtt:
          - TestFunctionServiceRole
          - Arn
      Runtime: python3.6
    DependsOn:
      - TestFunctionServiceRole
